### ISSUE TITLE
The building has broken since some recent commits in pairing

### ISSUE THREAD

**Issue by noel2004** [appliedzkp/halo2#18]
Recently when building with halo2, cargo has complained like these:

>    Compiling halo2 v0.1.0-beta.1 (https://github.com/appliedzkp/halo2.git#a970e575)
error[E0599]: no function or associated item named `read` found for associated type `<E as pairing_bn256::arithmetic::Engine>::G2Affine` in the current scope
   --> /home/combray/.cargo/git/checkouts/halo2-b8251ca10f182e2b/a970e57/src/poly/commitment.rs:124:33
    |
124 |         let s_g2 = E::G2Affine::read(&mut additional_data.as_slice())?;
    |                                 ^^^^ function or associated item not found in `<E as pairing_bn256::arithmetic::Engine>::G2Affine`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use crate::helpers::CurveRead;`

> error[E0599]: no function or associated item named `read` found for type parameter `C` in the current scope
   --> /home/combray/.cargo/git/checkouts/halo2-b8251ca10f182e2b/a970e57/src/poly/commitment.rs:197:25
    |
197 |             .map(|_| C::read(&mut reader))
    |                         ^^^^ function or associated item not found in `C`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use crate::helpers::CurveRead;`

Because halo2 has dependencies on the newest commit of pairing, I can only recover if I had locked the version of pairings to commit [18f6e63242922c4845347623cd440b9ac9ecc040](https://github.com/appliedzkp/pairing/commit/18f6e63242922c4845347623cd440b9ac9ecc040).

I guess the error has been induced by commit inside pairing [4308e0f2f5badcf019c971e47fe6b6febb399d8](https://github.com/appliedzkp/pairing/commit/44308e0f2f5badcf019c971e47fe6b6febb399d8#diff-f3d800b9a927254ba1c14e7cb02f4b0684121062fcfce791e99efc386a33ae4e), in which the read / write method has been removed from CurveAffine trait

**Comment by CPerezz** [comment]
That's solved now in zkevm-circuits with the update to the latest release of Halo2.
