### ISSUE TITLE
Bench regression improvement not working

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/halo2#39]
Once #38 was merged, the workflow: https://github.com/appliedzkp/halo2/runs/5438063316?check_suite_focus=true failed returning no output logs at all. 

We should try to see what's going on and fix it. Or remove it if we don;t want it.

**Comment by CPerezz** [comment]
@ntampakas @AronisAt79 Can I assign this to you?? 
This has got no updates yet

**Comment by ntampakas** [comment]
Sure @CPerezz .
We will check it out.

**Comment by CPerezz** [comment]
I've never ever seen that flag lol. Why not deviate the stdout to  afile directly? @ntampakas

**Comment by ntampakas** [comment]
We will create a PR with an updated version of the workflow, with that flag removed :)

**Comment by CPerezz** [comment]
Nice!! That would be useful so that we can check results in the PR directly! :)

**Comment by ntampakas** [comment]
As discussed internally, we decided to remove this workflow since we have our own benches.
